[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "joblib>=1.5.1",
    "numpy>=2.2.6",
    "pydantic>=2.11.7",
    "scikit-learn>=1.7.1",
    "uvicorn>=0.35.0",
]
